baseURL = "https://azul.technology/"
languageCode = "en-us"
pluralizeListTitles = false
title = "Azul Technology"
enableEmoji = true
[params]
custom_css = []
custom_js = []
description = "Azul Technology"
googleAnalytics = "UA-33330753-1"
favicon = "favicon.ico"
image = ""
name = "Gabriel Wilkes"
[params.banner]
buttontext = "Get Started"
subtitle = "Proven web design and e-commerce, get in touch today"
title = "Launching websites since 2007"
[params.contact]
buttonclear = "Clear"
buttonsend = "Send message"
enable = true
[[params.contact.address]]
city = "Frisco, TX 75035"
country = "USA"
street = "15699 Wrangler Dr"
title = "Address"
[[params.contact.email]]
email = "gabriel@azultech.com"
email_url = "mailto:gabriel@azultech.com?Subject=Hello%20Gabriel"
title = "Email"
[[params.contact.phone]]
phone = "+1 (714) 758-5275"
title = "Phone"
[params.error404]
heading = "404"
text = "Sorry, page couldn't be found!"
[params.footer]
copyright = "Azul Technology"
enable = true
[[params.footer.social]]
icon = "fa-twitter"
label = "Twitter"
url = "https://twitter.com/gabriel_wilkes"
[[params.footer.social]]
icon = "fa-facebook"
label = "Facebook"
url = "https://www.facebook.com/gabrielwilkes"
[[params.footer.social]]
icon = "fa-instagram"
label = "Instagram"
url = "https://www.instagram.com/gwilkes/"
[[params.footer.social]]
icon = "fa-github"
label = "GitHub"
url = "https://github.com/gabriel-wilkes"
[[params.footer.social]]
icon = "fa-linkedin"
label = "LinkedIn"
url = "https://www.linkedin.com/in/gabrielwilkes/"
[params.navigation]
menu = "Menu"
subtitle = "By Gabriel Wilkes"
title = "Azul Technology"
[[params.navigation.button2]]
name = "Contact"
url = "/index.html#contact"
[[params.navigation.links]]
name = "Home"
url = "/"
[[params.navigation.links]]
name = "About"
url = "/index.html#about"
[[params.navigation.links]]
name = "Portfolio"
url = "/portfolio"
[[params.navigation.links]]
name = "Uses"
url = "/uses"
[[params.navigation.links]]
name = "Blog"
url = "https://medium.com/@gabriel_wilkes"
[params.tiles]
enable = true
[[params.tiles.showcase]]
image = "gordon-graham.jpg"
subtitle = "E-commerce site for sunglasses"
title = "Gordon Graham"
url = "portfolio/gordon-graham"
[[params.tiles.showcase]]
image = "uramune.jpg"
subtitle = "Bilingual e-commerce site for silk dresses"
title = "Uramuné"
url = "portfolio/uramune"
[[params.tiles.showcase]]
image = "cedros.jpg"
subtitle = "Award winning Californian seafood in Tokyo"
title = "Cedros"
url = "portfolio/cedros"
[[params.tiles.showcase]]
image = "cabin.jpg"
subtitle = "Rustic whiskey and cocktail bar"
title = "Cabin"
url = "portfolio/cabin"
[[params.tiles.showcase]]
image = "yellowcab.jpg"
subtitle = "Ebook interactivity using JavaScript"
title = "Yellow Cab of the Universe"
url = "portfolio/yellow-cab"
[[params.tiles.showcase]]
image = "makertoolset.jpg"
subtitle = "Technology clubs and workshops"
title = "Maker Toolset"
url = "portfolio/maker-toolset"
[params.two]
buttontext = "Blog"
enable = true
paragraph = "Gabriel Wilkes started Azul Technology in 2007 to provide IT and web development \nservices to small and medium businesses in San Diego, California. In 2010 Gabriel \nmoved to a suburb of Tokyo and began to focus more on web development."
paragraph2 = "    Over time Azul Technology's specialties became web apps and e-commerce. Gabriel has implemented web apps using various platforms and technolgies, from the traditional LAMP stack all the way to Vue.js with a serverless AWS backend. For e-commerce sites, Gabriel has created or worked on them using 5 different platforms including WooCommerce and Shopify. \n    If you would like to learn more please contact me or visit the social links at the bottom of the page.\n    Thanks for stopping by!"
title = "About"
url = "https://medium.com/@gabriel_wilkes"
